version: '3.2'

services: 
    node1:
        build: 
            context: .
            dockerfile: './compose/webapp/Dockerfile-node'
    
        command:
            - python
            - node_server.py
    
    node2:
        build: 
            context: .
            dockerfile: './compose/webapp/Dockerfile-node'
    
        command:
            - python
            - node_server.py
    node3:
        build: 
            context: .
            dockerfile: './compose/webapp/Dockerfile-node'
    
        command:
            - python
            - node_server.py


    webapp:
        build:
            context: .
            dockerfile: './compose/webapp/Dockerfile-dev'
        
        ports:
            - "5000:5000"
        
        command: 
            - python3
            - run_app.py
